### ISSUE TITLE
Implement Bank View

### ISSUE THREAD

**Issue by hofbi** [objective/lunch-conFIRMed#3]
* Add implementation to `bank.html` and `BankView` class
  * Page should just be visible for admins
  * Build the template view similar to our local table
    * List with all users (name & credit, field to add new credit)
    * List with all lunchs (date & bill) and field to add bill value to lunch (should also save to db)
  * Add also functionality of our local table

**Comment by lostdesign** [comment]
Progress on base view: ![image](https://i.imgur.com/0U8dClt.png)

**Comment by hofbi** [comment]
Added basic bank view in Commit d981a110c30cde85f26357acef5e5feb31487f70

Remaining Tasks:
- [ ] Add forms to update the DB (marked as TODO in the code)
- [ ] Add SCSS stuff
